env:
  - CONVERTER=ffmpeg
  - CONVERTER=libav-tools
before_install:
  - sudo apt-get update --fix-missing
install:
  - pip install coveralls
  - sudo apt-get install -y ${CONVERTER} libavcodec-extra-53 ubuntu-restricted-extras #gstreamer0.10-ffmpeg gstreamer0.10-plugins-ugly gstreamer0.10-plugins-bad gstreamer0.10-plugins-bad-multiverse
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
script:
  - python test/test.py
#  - coverage run --source=pydub --omit="pydub/pyaudioop.py" test/test.py
#  - coverage report -m
#after_script:
#  coveralls --verbose

